# Generated by Django 5.2.9 on 2025-12-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_category_user_categories'),
        ('articles', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(to='articles.category'),
        ),
    ]
