# Generated by Django 5.2.9 on 2025-12-19 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('isbn', models.CharField(max_length=20)),
                ('cover', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('author_info', models.CharField(max_length=500)),
                ('author_photo', models.CharField(max_length=300)),
                ('customer_review_rank', models.IntegerField(blank=True, null=True)),
                ('subTitle', models.CharField(max_length=50)),
                ('recommends', models.ManyToManyField(blank=True, related_name='recommended_by', to='articles.book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='articles.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.book')),
            ],
        ),
    ]
