# Generated by Django 5.2.9 on 2025-12-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_book_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
    ]
